site_name: Useful Utility
site_url: https://sirmrmanuel0.github.io/usefull_utility_py/
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
- mkdocstrings

nav:
  - "Matrix": Matrix.md
