site_name: Useful Utility
site_url: https://sirmrmanuel0.github.io/usefull_utility_py/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        primary: light blue
        accent: light blue

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        primary: deep purple
        accent: deep purple

plugins:
  - mkdocstrings
  - search:
      lang:
        - en
        - fr

nav:
  - "Matrix": Matrix.md
